### ISSUE TITLE
I want a C koans.

### ISSUE THREAD

**Issue by WyattJia** [ts25504/awesome-koans#2]
Whatever ANSI C or GNU C, thanks.

**Comment by mlavina** [comment]
I have used https://github.com/c-koans/c_koans and it was pretty good. 

It should probably be added to the list

**Comment by WyattJia** [comment]
@mlavina looks great, maybe we should create a pull request for this.

**Comment by ts25504** [comment]
Thank you for your suggestion. I've already added the C koans to the list.
